(in-package :cobweb)

(defparameter *elem-tags* (make-hash-table))

(defclass xhtml-meta (c2mop:funcallable-standard-class)
  ((is-tag :initarg :is-tag :accessor is-tag))
  (:documentation "The HTML metaclass."))

;; TODO: this precedence is awkward
(defclass fragment-meta (xhtml-meta)
  ((layout :initarg :layout :accessor fragment-layout)))

(defmethod c2mop:validate-superclass  
    ((class xhtml-meta) (super c2mop:funcallable-standard-class))  
  t)

(defmethod c2mop:validate-superclass  
    ((class fragment-meta) (super xhtml-meta))  
  t)

(c2mop:ensure-finalized (find-class 'xhtml-meta))
(c2mop:ensure-finalized (find-class 'fragment-meta))

(defmacro deftag (name)
  `(let* ((class-name ',(read-from-string
                         (format nil "~@:(elem-~a~)"
                                 name)))
          (attrs (expose-tag (c2mop:class-slots (find-class class-name))
                             :add-slots)))
     (defmacro ,name (&body body)
       ;; TODO: nested macros aren't evaluating
       `(macrolet ((rec (body)
                     (list ,@body)))
          (destructuring-bind (&key attrs body)
              ',(parse-attrs body attrs)
            (apply #'make-instance ',class-name
                   :body ,`(apply #'vector (rec ,@body))
                   attrs))))))

(defgeneric expose-tag (class key)
  (:documentation "Describes how to make a class parseable."))

(defmethod expose-tag :before ((class xhtml-meta) key)
  (declare (ignore key))
  (c2mop:ensure-finalized class))

(defmethod expose-tag (class (key null))
  t)

(defmethod expose-tag (class key)
  (setf (gethash (is-tag class) *elem-tags*)
        (expose-tag (c2mop:class-slots class) :add-slots))
  t)

(defmethod expose-tag ((slots list) (key (eql :add-slots)))
  (loop for slot in slots
        as slot-name = (symbol-name (c2mop:slot-definition-name slot))
        when (search "ATTR-" slot-name)
          collect (car (c2mop:slot-definition-initargs slot))))

(defmethod expose-tag ((class xhtml-meta) (key (eql :elem)))
  (let ((tag (intern (subseq (symbol-name (class-name class)) 5) :keyword)))
    (setf (gethash tag *elem-tags*)
          (cons (class-name class)
                (expose-tag (c2mop:class-slots class) :add-slots)))
    t))

(defmethod initialize-instance :after ((class xhtml-meta)
                                       &key (tag '(:elem)) &allow-other-keys)
  (setf (is-tag class) tag)
  (expose-tag class (car tag)))

(defmethod reinitialize-instance :after ((class xhtml-meta)
                                         &key (tag '(:elem)) &allow-other-keys)
  (setf (is-tag class) tag)
  (expose-tag class (car tag)))

(defclass fragment ()
  ((parent    :initarg :parent :accessor parent)
   (coords    :initarg :coords :accessor coords)
   (html-body :initarg :body   :accessor html-body))
  (:metaclass fragment-meta)
  (:documentation "An abstract middleware class between XHTML and every
HTML element.")
  (:tag nil))

(defclass xhtml (fragment) ()
  (:metaclass xhtml-meta)
  (:tag nil)
  (:default-initargs
   :parent :root))

(defclass non-conforming-features () ()
  (:metaclass xhtml-meta)
  (:tag nil))


;; begin autogenerate at 2025-03-05T18:34:30.699762-08:00
(defclass elem-global (xhtml)
  ((attr-slot :initarg :slot :accessor attr-slot)
   (attr-id :initarg :id :accessor attr-id)
   (attr-class :initarg :class :accessor attr-class)
   (attr-popovertargetaction :initarg :popovertargetaction :accessor attr-popovertargetaction)
   (attr-popovertarget :initarg :popovertarget :accessor attr-popovertarget)
   (attr-popover :initarg :popover :accessor attr-popover)
   (attr-draggable :initarg :draggable :accessor attr-draggable)
   (attr-enterkeyhint :initarg :enterkeyhint :accessor attr-enterkeyhint)
   (attr-inputmode :initarg :inputmode :accessor attr-inputmode)
   (attr-autocorrect :initarg :autocorrect :accessor attr-autocorrect)
   (attr-autocapitalize :initarg :autocapitalize :accessor attr-autocapitalize)
   (attr-writingsuggestions :initarg :writingsuggestions :accessor attr-writingsuggestions)
   (attr-spellcheck :initarg :spellcheck :accessor attr-spellcheck)
   (attr-contenteditable :initarg :contenteditable :accessor attr-contenteditable)
   (attr-accesskey :initarg :accesskey :accessor attr-accesskey)
   (attr-autofocus :initarg :autofocus :accessor attr-autofocus)
   (attr-hidden :initarg :hidden :accessor attr-hidden)
   (attr-itemprop :initarg :itemprop :accessor attr-itemprop)
   (attr-itemref :initarg :itemref :accessor attr-itemref)
   (attr-itemid :initarg :itemid :accessor attr-itemid)
   (attr-itemtype :initarg :itemtype :accessor attr-itemtype)
   (attr-itemscope :initarg :itemscope :accessor attr-itemscope)
   (attr-is :initarg :is :accessor attr-is)
   (attr-style :initarg :style :accessor attr-style)
   (attr-dir :initarg :dir :accessor attr-dir)
   (attr-translate :initarg :translate :accessor attr-translate)
   (attr-lang :initarg :lang :accessor attr-lang)
   (attr-title :initarg :title :accessor attr-title))
  (:metaclass xhtml-meta)
  (:tag nil))

(defclass elem-frame (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-frameset (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-marquee (elem-global fragment)
  ((attr-loop :initarg :loop :accessor attr-loop)
   (attr-truespeed :initarg :truespeed :accessor attr-truespeed)
   (attr-direction :initarg :direction :accessor attr-direction)
   (attr-behavior :initarg :behavior :accessor attr-behavior))
  (:metaclass xhtml-meta))

(defclass elem-tt (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-spacer (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-nobr (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-multicol (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-font (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-center (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-blink (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-big (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-basefont (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-xmp (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-strike (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-rtc (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-rb (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-plaintext (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-param (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-noembed (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-nextid (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-menuitem (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-listing (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-keygen (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-isindex (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-noframes (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-dir (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-bgsound (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-acronym (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-applet (elem-global fragment non-conforming-features) ()
  (:metaclass xhtml-meta))

(defclass elem-canvas (elem-global fragment)
  ((attr-height :initarg :height :accessor attr-height)
   (attr-width :initarg :width :accessor attr-width))
  (:metaclass xhtml-meta))

(defclass elem-slot (elem-global fragment)
  ((attr-name :initarg :name :accessor attr-name))
  (:metaclass xhtml-meta))

(defclass elem-template (elem-global fragment)
  ((attr-shadowrootserializable :initarg :shadowrootserializable :accessor attr-shadowrootserializable)
   (attr-shadowrootclonable :initarg :shadowrootclonable :accessor attr-shadowrootclonable)
   (attr-shadowrootdelegatesfocus :initarg :shadowrootdelegatesfocus :accessor attr-shadowrootdelegatesfocus)
   (attr-shadowrootmode :initarg :shadowrootmode :accessor attr-shadowrootmode))
  (:metaclass xhtml-meta))

(defclass elem-noscript (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-script (elem-global fragment)
  ((attr-for :initarg :for :accessor attr-for)
   (attr-event :initarg :event :accessor attr-event)
   (attr-language :initarg :language :accessor attr-language)
   (attr-charset :initarg :charset :accessor attr-charset)
   (attr-fetchpriority :initarg :fetchpriority :accessor attr-fetchpriority)
   (attr-blocking :initarg :blocking :accessor attr-blocking)
   (attr-referrerpolicy :initarg :referrerpolicy :accessor attr-referrerpolicy)
   (attr-integrity :initarg :integrity :accessor attr-integrity)
   (attr-crossorigin :initarg :crossorigin :accessor attr-crossorigin)
   (attr-defer :initarg :defer :accessor attr-defer)
   (attr-async :initarg :async :accessor attr-async)
   (attr-nomodule :initarg :nomodule :accessor attr-nomodule)
   (attr-src :initarg :src :accessor attr-src)
   (attr-type :initarg :type :accessor attr-type))
  (:metaclass xhtml-meta))

(defclass elem-dialog (elem-global fragment)
  ((attr-closedby :initarg :closedby :accessor attr-closedby)
   (attr-open :initarg :open :accessor attr-open))
  (:metaclass xhtml-meta))

(defclass elem-summary (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-details (elem-global fragment)
  ((attr-open :initarg :open :accessor attr-open)
   (attr-name :initarg :name :accessor attr-name))
  (:metaclass xhtml-meta))

(defclass elem-legend (elem-global fragment)
  ((attr-align :initarg :align :accessor attr-align))
  (:metaclass xhtml-meta))

(defclass elem-fieldset (elem-global fragment)
  ((attr-autocomplete :initarg :autocomplete :accessor attr-autocomplete)
   (attr-name :initarg :name :accessor attr-name)
   (attr-form :initarg :form :accessor attr-form)
   (attr-disabled :initarg :disabled :accessor attr-disabled))
  (:metaclass xhtml-meta))

(defclass elem-meter (elem-global fragment)
  ((attr-optimum :initarg :optimum :accessor attr-optimum)
   (attr-high :initarg :high :accessor attr-high)
   (attr-low :initarg :low :accessor attr-low)
   (attr-value :initarg :value :accessor attr-value)
   (attr-max :initarg :max :accessor attr-max)
   (attr-min :initarg :min :accessor attr-min))
  (:metaclass xhtml-meta))

(defclass elem-progress (elem-global fragment)
  ((attr-max :initarg :max :accessor attr-max)
   (attr-value :initarg :value :accessor attr-value))
  (:metaclass xhtml-meta))

(defclass elem-output (elem-global fragment)
  ((attr-autocomplete :initarg :autocomplete :accessor attr-autocomplete)
   (attr-disabled :initarg :disabled :accessor attr-disabled)
   (attr-name :initarg :name :accessor attr-name)
   (attr-form :initarg :form :accessor attr-form)
   (attr-for :initarg :for :accessor attr-for))
  (:metaclass xhtml-meta))

(defclass elem-textarea (elem-global fragment)
  ((attr-autocomplete :initarg :autocomplete :accessor attr-autocomplete)
   (attr-disabled :initarg :disabled :accessor attr-disabled)
   (attr-dirname :initarg :dirname :accessor attr-dirname)
   (attr-name :initarg :name :accessor attr-name)
   (attr-form :initarg :form :accessor attr-form)
   (attr-placeholder :initarg :placeholder :accessor attr-placeholder)
   (attr-required :initarg :required :accessor attr-required)
   (attr-minlength :initarg :minlength :accessor attr-minlength)
   (attr-maxlength :initarg :maxlength :accessor attr-maxlength)
   (attr-wrap :initarg :wrap :accessor attr-wrap)
   (attr-rows :initarg :rows :accessor attr-rows)
   (attr-cols :initarg :cols :accessor attr-cols)
   (attr-readonly :initarg :readonly :accessor attr-readonly))
  (:metaclass xhtml-meta))

(defclass elem-option (elem-global fragment)
  ((attr-name :initarg :name :accessor attr-name)
   (attr-selected :initarg :selected :accessor attr-selected)
   (attr-value :initarg :value :accessor attr-value)
   (attr-label :initarg :label :accessor attr-label)
   (attr-disabled :initarg :disabled :accessor attr-disabled))
  (:metaclass xhtml-meta))

(defclass elem-optgroup (elem-global fragment)
  ((attr-label :initarg :label :accessor attr-label)
   (attr-disabled :initarg :disabled :accessor attr-disabled))
  (:metaclass xhtml-meta))

(defclass elem-datalist (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-select (elem-global fragment)
  ((attr-autocomplete :initarg :autocomplete :accessor attr-autocomplete)
   (attr-disabled :initarg :disabled :accessor attr-disabled)
   (attr-name :initarg :name :accessor attr-name)
   (attr-form :initarg :form :accessor attr-form)
   (attr-required :initarg :required :accessor attr-required)
   (attr-size :initarg :size :accessor attr-size)
   (attr-multiple :initarg :multiple :accessor attr-multiple))
  (:metaclass xhtml-meta))

(defclass elem-button (elem-global fragment)
  ((attr-autocomplete :initarg :autocomplete :accessor attr-autocomplete)
   (attr-formnovalidate :initarg :formnovalidate :accessor attr-formnovalidate)
   (attr-novalidate :initarg :novalidate :accessor attr-novalidate)
   (attr-formtarget :initarg :formtarget :accessor attr-formtarget)
   (attr-target :initarg :target :accessor attr-target)
   (attr-formenctype :initarg :formenctype :accessor attr-formenctype)
   (attr-enctype :initarg :enctype :accessor attr-enctype)
   (attr-formmethod :initarg :formmethod :accessor attr-formmethod)
   (attr-method :initarg :method :accessor attr-method)
   (attr-formaction :initarg :formaction :accessor attr-formaction)
   (attr-action :initarg :action :accessor attr-action)
   (attr-disabled :initarg :disabled :accessor attr-disabled)
   (attr-name :initarg :name :accessor attr-name)
   (attr-form :initarg :form :accessor attr-form)
   (attr-value :initarg :value :accessor attr-value)
   (attr-command :initarg :command :accessor attr-command)
   (attr-commandfor :initarg :commandfor :accessor attr-commandfor)
   (attr-type :initarg :type :accessor attr-type))
  (:metaclass xhtml-meta))

(defclass elem-input (elem-global fragment)
  ((attr-vspace :initarg :vspace :accessor attr-vspace)
   (attr-hspace :initarg :hspace :accessor attr-hspace)
   (attr-border :initarg :border :accessor attr-border)
   (attr-align :initarg :align :accessor attr-align)
   (attr-usemap :initarg :usemap :accessor attr-usemap)
   (attr-ismap :initarg :ismap :accessor attr-ismap)
   (attr-autocomplete :initarg :autocomplete :accessor attr-autocomplete)
   (attr-disabled :initarg :disabled :accessor attr-disabled)
   (attr-dirname :initarg :dirname :accessor attr-dirname)
   (attr-name :initarg :name :accessor attr-name)
   (attr-form :initarg :form :accessor attr-form)
   (attr-placeholder :initarg :placeholder :accessor attr-placeholder)
   (attr-list :initarg :list :accessor attr-list)
   (attr-step :initarg :step :accessor attr-step)
   (attr-max :initarg :max :accessor attr-max)
   (attr-min :initarg :min :accessor attr-min)
   (attr-title :initarg :title :accessor attr-title)
   (attr-pattern :initarg :pattern :accessor attr-pattern)
   (attr-multiple :initarg :multiple :accessor attr-multiple)
   (attr-required :initarg :required :accessor attr-required)
   (attr-readonly :initarg :readonly :accessor attr-readonly)
   (attr-size :initarg :size :accessor attr-size)
   (attr-minlength :initarg :minlength :accessor attr-minlength)
   (attr-maxlength :initarg :maxlength :accessor attr-maxlength)
   (attr-alt :initarg :alt :accessor attr-alt)
   (attr-src :initarg :src :accessor attr-src)
   (attr-accept :initarg :accept :accessor attr-accept)
   (attr-colorspace :initarg :colorspace :accessor attr-colorspace)
   (attr-alpha :initarg :alpha :accessor attr-alpha)
   (attr-checked :initarg :checked :accessor attr-checked)
   (attr-value :initarg :value :accessor attr-value)
   (attr-type :initarg :type :accessor attr-type))
  (:metaclass xhtml-meta))

(defclass elem-label (elem-global fragment)
  ((attr-for :initarg :for :accessor attr-for))
  (:metaclass xhtml-meta))

(defclass elem-form (elem-global fragment)
  ((attr-accept :initarg :accept :accessor attr-accept)
   (attr-formnovalidate :initarg :formnovalidate :accessor attr-formnovalidate)
   (attr-novalidate :initarg :novalidate :accessor attr-novalidate)
   (attr-formtarget :initarg :formtarget :accessor attr-formtarget)
   (attr-target :initarg :target :accessor attr-target)
   (attr-formenctype :initarg :formenctype :accessor attr-formenctype)
   (attr-enctype :initarg :enctype :accessor attr-enctype)
   (attr-formmethod :initarg :formmethod :accessor attr-formmethod)
   (attr-method :initarg :method :accessor attr-method)
   (attr-formaction :initarg :formaction :accessor attr-formaction)
   (attr-action :initarg :action :accessor attr-action)
   (attr-rel :initarg :rel :accessor attr-rel)
   (attr-autocomplete :initarg :autocomplete :accessor attr-autocomplete)
   (attr-name :initarg :name :accessor attr-name)
   (attr-accept-charset :initarg :accept-charset :accessor attr-accept-charset))
  (:metaclass xhtml-meta))

(defclass elem-th (elem-global fragment)
  ((attr-width :initarg :width :accessor attr-width)
   (attr-valign :initarg :valign :accessor attr-valign)
   (attr-nowrap :initarg :nowrap :accessor attr-nowrap)
   (attr-height :initarg :height :accessor attr-height)
   (attr-charoff :initarg :charoff :accessor attr-charoff)
   (attr-char :initarg :char :accessor attr-char)
   (attr-bgcolor :initarg :bgcolor :accessor attr-bgcolor)
   (attr-align :initarg :align :accessor attr-align)
   (attr-axis :initarg :axis :accessor attr-axis)
   (attr-headers :initarg :headers :accessor attr-headers)
   (attr-rowspan :initarg :rowspan :accessor attr-rowspan)
   (attr-colspan :initarg :colspan :accessor attr-colspan)
   (attr-abbr :initarg :abbr :accessor attr-abbr)
   (attr-scope :initarg :scope :accessor attr-scope))
  (:metaclass xhtml-meta))

(defclass elem-td (elem-global fragment)
  ((attr-width :initarg :width :accessor attr-width)
   (attr-valign :initarg :valign :accessor attr-valign)
   (attr-nowrap :initarg :nowrap :accessor attr-nowrap)
   (attr-height :initarg :height :accessor attr-height)
   (attr-charoff :initarg :charoff :accessor attr-charoff)
   (attr-char :initarg :char :accessor attr-char)
   (attr-bgcolor :initarg :bgcolor :accessor attr-bgcolor)
   (attr-align :initarg :align :accessor attr-align)
   (attr-scope :initarg :scope :accessor attr-scope)
   (attr-axis :initarg :axis :accessor attr-axis)
   (attr-abbr :initarg :abbr :accessor attr-abbr)
   (attr-headers :initarg :headers :accessor attr-headers)
   (attr-rowspan :initarg :rowspan :accessor attr-rowspan)
   (attr-colspan :initarg :colspan :accessor attr-colspan))
  (:metaclass xhtml-meta))

(defclass elem-tr (elem-global fragment)
  ((attr-valign :initarg :valign :accessor attr-valign)
   (attr-height :initarg :height :accessor attr-height)
   (attr-charoff :initarg :charoff :accessor attr-charoff)
   (attr-char :initarg :char :accessor attr-char)
   (attr-bgcolor :initarg :bgcolor :accessor attr-bgcolor)
   (attr-align :initarg :align :accessor attr-align))
  (:metaclass xhtml-meta))

(defclass elem-tfoot (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-thead (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-tbody (elem-global fragment)
  ((attr-valign :initarg :valign :accessor attr-valign)
   (attr-height :initarg :height :accessor attr-height)
   (attr-charoff :initarg :charoff :accessor attr-charoff)
   (attr-char :initarg :char :accessor attr-char)
   (attr-align :initarg :align :accessor attr-align))
  (:metaclass xhtml-meta))

(defclass elem-col (elem-global fragment)
  ((attr-width :initarg :width :accessor attr-width)
   (attr-valign :initarg :valign :accessor attr-valign)
   (attr-charoff :initarg :charoff :accessor attr-charoff)
   (attr-char :initarg :char :accessor attr-char)
   (attr-align :initarg :align :accessor attr-align)
   (attr-span :initarg :span :accessor attr-span))
  (:metaclass xhtml-meta))

(defclass elem-colgroup (elem-global fragment)
  ((attr-span :initarg :span :accessor attr-span))
  (:metaclass xhtml-meta))

(defclass elem-caption (elem-global fragment)
  ((attr-align :initarg :align :accessor attr-align))
  (:metaclass xhtml-meta))

(defclass elem-table (elem-global fragment)
  ((attr-width :initarg :width :accessor attr-width)
   (attr-rules :initarg :rules :accessor attr-rules)
   (attr-height :initarg :height :accessor attr-height)
   (attr-frame :initarg :frame :accessor attr-frame)
   (attr-cellspacing :initarg :cellspacing :accessor attr-cellspacing)
   (attr-cellpadding :initarg :cellpadding :accessor attr-cellpadding)
   (attr-bordercolor :initarg :bordercolor :accessor attr-bordercolor)
   (attr-border :initarg :border :accessor attr-border)
   (attr-bgcolor :initarg :bgcolor :accessor attr-bgcolor)
   (attr-align :initarg :align :accessor attr-align)
   (attr-summary :initarg :summary :accessor attr-summary)
   (attr-datapagesize :initarg :datapagesize :accessor attr-datapagesize))
  (:metaclass xhtml-meta))

(defclass elem-area (elem-global fragment)
  ((attr-nohref :initarg :nohref :accessor attr-nohref)
   (attr-coords :initarg :coords :accessor attr-coords)
   (attr-shape :initarg :shape :accessor attr-shape)
   (attr-alt :initarg :alt :accessor attr-alt)
   (attr-referrerpolicy :initarg :referrerpolicy :accessor attr-referrerpolicy)
   (attr-type :initarg :type :accessor attr-type)
   (attr-hreflang :initarg :hreflang :accessor attr-hreflang)
   (attr-rel :initarg :rel :accessor attr-rel)
   (attr-ping :initarg :ping :accessor attr-ping)
   (attr-download :initarg :download :accessor attr-download)
   (attr-target :initarg :target :accessor attr-target)
   (attr-href :initarg :href :accessor attr-href))
  (:metaclass xhtml-meta))

(defclass elem-map (elem-global fragment)
  ((attr-name :initarg :name :accessor attr-name))
  (:metaclass xhtml-meta))

(defclass elem-track (elem-global fragment)
  ((attr-default :initarg :default :accessor attr-default)
   (attr-label :initarg :label :accessor attr-label)
   (attr-srclang :initarg :srclang :accessor attr-srclang)
   (attr-src :initarg :src :accessor attr-src)
   (attr-kind :initarg :kind :accessor attr-kind))
  (:metaclass xhtml-meta))

(defclass elem-audio (elem-global fragment)
  ((attr-muted :initarg :muted :accessor attr-muted)
   (attr-controls :initarg :controls :accessor attr-controls)
   (attr-autoplay :initarg :autoplay :accessor attr-autoplay)
   (attr-loop :initarg :loop :accessor attr-loop)
   (attr-preload :initarg :preload :accessor attr-preload)
   (attr-crossorigin :initarg :crossorigin :accessor attr-crossorigin)
   (attr-src :initarg :src :accessor attr-src))
  (:metaclass xhtml-meta))

(defclass elem-video (elem-global fragment)
  ((attr-height :initarg :height :accessor attr-height)
   (attr-width :initarg :width :accessor attr-width)
   (attr-muted :initarg :muted :accessor attr-muted)
   (attr-controls :initarg :controls :accessor attr-controls)
   (attr-autoplay :initarg :autoplay :accessor attr-autoplay)
   (attr-loop :initarg :loop :accessor attr-loop)
   (attr-preload :initarg :preload :accessor attr-preload)
   (attr-crossorigin :initarg :crossorigin :accessor attr-crossorigin)
   (attr-src :initarg :src :accessor attr-src)
   (attr-playsinline :initarg :playsinline :accessor attr-playsinline)
   (attr-poster :initarg :poster :accessor attr-poster))
  (:metaclass xhtml-meta))

(defclass elem-object (elem-global fragment)
  ((attr-vspace :initarg :vspace :accessor attr-vspace)
   (attr-hspace :initarg :hspace :accessor attr-hspace)
   (attr-border :initarg :border :accessor attr-border)
   (attr-align :initarg :align :accessor attr-align)
   (attr-typemustmatch :initarg :typemustmatch :accessor attr-typemustmatch)
   (attr-standby :initarg :standby :accessor attr-standby)
   (attr-declare :initarg :declare :accessor attr-declare)
   (attr-codetype :initarg :codetype :accessor attr-codetype)
   (attr-codebase :initarg :codebase :accessor attr-codebase)
   (attr-code :initarg :code :accessor attr-code)
   (attr-classid :initarg :classid :accessor attr-classid)
   (attr-archive :initarg :archive :accessor attr-archive)
   (attr-usemap :initarg :usemap :accessor attr-usemap)
   (attr-autocomplete :initarg :autocomplete :accessor attr-autocomplete)
   (attr-disabled :initarg :disabled :accessor attr-disabled)
   (attr-form :initarg :form :accessor attr-form)
   (attr-height :initarg :height :accessor attr-height)
   (attr-width :initarg :width :accessor attr-width)
   (attr-name :initarg :name :accessor attr-name)
   (attr-type :initarg :type :accessor attr-type)
   (attr-data :initarg :data :accessor attr-data))
  (:metaclass xhtml-meta))

(defclass elem-embed (elem-global fragment)
  ((attr-vspace :initarg :vspace :accessor attr-vspace)
   (attr-hspace :initarg :hspace :accessor attr-hspace)
   (attr-align :initarg :align :accessor attr-align)
   (attr-name :initarg :name :accessor attr-name)
   (attr-height :initarg :height :accessor attr-height)
   (attr-width :initarg :width :accessor attr-width)
   (attr-type :initarg :type :accessor attr-type)
   (attr-src :initarg :src :accessor attr-src))
  (:metaclass xhtml-meta))

(defclass elem-iframe (elem-global fragment)
  ((attr-vspace :initarg :vspace :accessor attr-vspace)
   (attr-scrolling :initarg :scrolling :accessor attr-scrolling)
   (attr-marginwidth :initarg :marginwidth :accessor attr-marginwidth)
   (attr-marginheight :initarg :marginheight :accessor attr-marginheight)
   (attr-hspace :initarg :hspace :accessor attr-hspace)
   (attr-framespacing :initarg :framespacing :accessor attr-framespacing)
   (attr-frameborder :initarg :frameborder :accessor attr-frameborder)
   (attr-allowtransparency :initarg :allowtransparency :accessor attr-allowtransparency)
   (attr-align :initarg :align :accessor attr-align)
   (attr-longdesc :initarg :longdesc :accessor attr-longdesc)
   (attr-height :initarg :height :accessor attr-height)
   (attr-width :initarg :width :accessor attr-width)
   (attr-loading :initarg :loading :accessor attr-loading)
   (attr-referrerpolicy :initarg :referrerpolicy :accessor attr-referrerpolicy)
   (attr-allowfullscreen :initarg :allowfullscreen :accessor attr-allowfullscreen)
   (attr-allow :initarg :allow :accessor attr-allow)
   (attr-sandbox :initarg :sandbox :accessor attr-sandbox)
   (attr-name :initarg :name :accessor attr-name)
   (attr-srcdoc :initarg :srcdoc :accessor attr-srcdoc)
   (attr-src :initarg :src :accessor attr-src))
  (:metaclass xhtml-meta))

(defclass elem-img (elem-global fragment)
  ((attr-vspace :initarg :vspace :accessor attr-vspace)
   (attr-hspace :initarg :hspace :accessor attr-hspace)
   (attr-border :initarg :border :accessor attr-border)
   (attr-align :initarg :align :accessor attr-align)
   (attr-lowsrc :initarg :lowsrc :accessor attr-lowsrc)
   (attr-longdesc :initarg :longdesc :accessor attr-longdesc)
   (attr-name :initarg :name :accessor attr-name)
   (attr-height :initarg :height :accessor attr-height)
   (attr-width :initarg :width :accessor attr-width)
   (attr-usemap :initarg :usemap :accessor attr-usemap)
   (attr-ismap :initarg :ismap :accessor attr-ismap)
   (attr-loading :initarg :loading :accessor attr-loading)
   (attr-fetchpriority :initarg :fetchpriority :accessor attr-fetchpriority)
   (attr-decoding :initarg :decoding :accessor attr-decoding)
   (attr-referrerpolicy :initarg :referrerpolicy :accessor attr-referrerpolicy)
   (attr-crossorigin :initarg :crossorigin :accessor attr-crossorigin)
   (attr-sizes :initarg :sizes :accessor attr-sizes)
   (attr-alt :initarg :alt :accessor attr-alt)
   (attr-srcset :initarg :srcset :accessor attr-srcset)
   (attr-src :initarg :src :accessor attr-src))
  (:metaclass xhtml-meta))

(defclass elem-source (elem-global fragment)
  ((attr-height :initarg :height :accessor attr-height)
   (attr-width :initarg :width :accessor attr-width)
   (attr-src :initarg :src :accessor attr-src)
   (attr-sizes :initarg :sizes :accessor attr-sizes)
   (attr-srcset :initarg :srcset :accessor attr-srcset)
   (attr-media :initarg :media :accessor attr-media)
   (attr-type :initarg :type :accessor attr-type))
  (:metaclass xhtml-meta))

(defclass elem-picture (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-del (elem-global fragment)
  ((attr-datetime :initarg :datetime :accessor attr-datetime)
   (attr-cite :initarg :cite :accessor attr-cite))
  (:metaclass xhtml-meta))

(defclass elem-ins (elem-global fragment)
  ((attr-datetime :initarg :datetime :accessor attr-datetime)
   (attr-cite :initarg :cite :accessor attr-cite))
  (:metaclass xhtml-meta))

(defclass elem-wbr (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-br (elem-global fragment)
  ((attr-clear :initarg :clear :accessor attr-clear))
  (:metaclass xhtml-meta))

(defclass elem-span (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-bdo (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-bdi (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-mark (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-u (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-b (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-i (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-sup (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-sub (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-kbd (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-samp (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-var (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-code (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-time (elem-global fragment)
  ((attr-datetime :initarg :datetime :accessor attr-datetime))
  (:metaclass xhtml-meta))

(defclass elem-data (elem-global fragment)
  ((attr-value :initarg :value :accessor attr-value))
  (:metaclass xhtml-meta))

(defclass elem-rp (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-rt (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-ruby (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-abbr (elem-global fragment)
  ((attr-title :initarg :title :accessor attr-title))
  (:metaclass xhtml-meta))

(defclass elem-dfn (elem-global fragment)
  ((attr-title :initarg :title :accessor attr-title))
  (:metaclass xhtml-meta))

(defclass elem-q (elem-global fragment)
  ((attr-cite :initarg :cite :accessor attr-cite))
  (:metaclass xhtml-meta))

(defclass elem-cite (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-s (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-small (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-strong (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-em (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-a (elem-global fragment)
  ((attr-urn :initarg :urn :accessor attr-urn)
   (attr-rev :initarg :rev :accessor attr-rev)
   (attr-name :initarg :name :accessor attr-name)
   (attr-methods :initarg :methods :accessor attr-methods)
   (attr-shape :initarg :shape :accessor attr-shape)
   (attr-coords :initarg :coords :accessor attr-coords)
   (attr-charset :initarg :charset :accessor attr-charset)
   (attr-referrerpolicy :initarg :referrerpolicy :accessor attr-referrerpolicy)
   (attr-type :initarg :type :accessor attr-type)
   (attr-hreflang :initarg :hreflang :accessor attr-hreflang)
   (attr-rel :initarg :rel :accessor attr-rel)
   (attr-ping :initarg :ping :accessor attr-ping)
   (attr-download :initarg :download :accessor attr-download)
   (attr-target :initarg :target :accessor attr-target)
   (attr-href :initarg :href :accessor attr-href))
  (:metaclass xhtml-meta))

(defclass elem-div (elem-global fragment)
  ((attr-align :initarg :align :accessor attr-align))
  (:metaclass xhtml-meta))

(defclass elem-search (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-main (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-figcaption (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-figure (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-dd (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-dt (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-dl (elem-global fragment)
  ((attr-compact :initarg :compact :accessor attr-compact))
  (:metaclass xhtml-meta))

(defclass elem-li (elem-global fragment)
  ((attr-type :initarg :type :accessor attr-type)
   (attr-value :initarg :value :accessor attr-value))
  (:metaclass xhtml-meta))

(defclass elem-menu (elem-global fragment)
  ((attr-compact :initarg :compact :accessor attr-compact)
   (attr-label :initarg :label :accessor attr-label)
   (attr-type :initarg :type :accessor attr-type))
  (:metaclass xhtml-meta))

(defclass elem-ul (elem-global fragment)
  ((attr-type :initarg :type :accessor attr-type)
   (attr-compact :initarg :compact :accessor attr-compact))
  (:metaclass xhtml-meta))

(defclass elem-ol (elem-global fragment)
  ((attr-compact :initarg :compact :accessor attr-compact)
   (attr-type :initarg :type :accessor attr-type)
   (attr-start :initarg :start :accessor attr-start)
   (attr-reversed :initarg :reversed :accessor attr-reversed))
  (:metaclass xhtml-meta))

(defclass elem-blockquote (elem-global fragment)
  ((attr-cite :initarg :cite :accessor attr-cite))
  (:metaclass xhtml-meta))

(defclass elem-pre (elem-global fragment)
  ((attr-width :initarg :width :accessor attr-width))
  (:metaclass xhtml-meta))

(defclass elem-hr (elem-global fragment)
  ((attr-width :initarg :width :accessor attr-width)
   (attr-size :initarg :size :accessor attr-size)
   (attr-noshade :initarg :noshade :accessor attr-noshade)
   (attr-color :initarg :color :accessor attr-color)
   (attr-align :initarg :align :accessor attr-align))
  (:metaclass xhtml-meta))

(defclass elem-p (elem-global fragment)
  ((attr-align :initarg :align :accessor attr-align))
  (:metaclass xhtml-meta))

(defclass elem-address (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-footer (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-header (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-hgroup (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-h6 (elem-global fragment)
  ((attr-align :initarg :align :accessor attr-align))
  (:metaclass xhtml-meta))

(defclass elem-h5 (elem-global fragment)
  ((attr-align :initarg :align :accessor attr-align))
  (:metaclass xhtml-meta))

(defclass elem-h4 (elem-global fragment)
  ((attr-align :initarg :align :accessor attr-align))
  (:metaclass xhtml-meta))

(defclass elem-h3 (elem-global fragment)
  ((attr-align :initarg :align :accessor attr-align))
  (:metaclass xhtml-meta))

(defclass elem-h2 (elem-global fragment)
  ((attr-align :initarg :align :accessor attr-align))
  (:metaclass xhtml-meta))

(defclass elem-h1 (elem-global fragment)
  ((attr-align :initarg :align :accessor attr-align))
  (:metaclass xhtml-meta))

(defclass elem-aside (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-nav (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-section (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-article (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-body (elem-global fragment)
  ((attr-vlink :initarg :vlink :accessor attr-vlink)
   (attr-topmargin :initarg :topmargin :accessor attr-topmargin)
   (attr-text :initarg :text :accessor attr-text)
   (attr-rightmargin :initarg :rightmargin :accessor attr-rightmargin)
   (attr-marginwidth :initarg :marginwidth :accessor attr-marginwidth)
   (attr-marginheight :initarg :marginheight :accessor attr-marginheight)
   (attr-link :initarg :link :accessor attr-link)
   (attr-leftmargin :initarg :leftmargin :accessor attr-leftmargin)
   (attr-bottommargin :initarg :bottommargin :accessor attr-bottommargin)
   (attr-bgcolor :initarg :bgcolor :accessor attr-bgcolor)
   (attr-alink :initarg :alink :accessor attr-alink))
  (:metaclass xhtml-meta))

(defclass elem-style (elem-global fragment)
  ((attr-type :initarg :type :accessor attr-type)
   (attr-title :initarg :title :accessor attr-title)
   (attr-blocking :initarg :blocking :accessor attr-blocking)
   (attr-media :initarg :media :accessor attr-media))
  (:metaclass xhtml-meta))

(defclass elem-meta (elem-global fragment)
  ((attr-scheme :initarg :scheme :accessor attr-scheme)
   (attr-http-equiv :initarg :http-equiv :accessor attr-http-equiv)
   (attr-media :initarg :media :accessor attr-media)
   (attr-name :initarg :name :accessor attr-name)
   (attr-content :initarg :content :accessor attr-content)
   (attr-charset :initarg :charset :accessor attr-charset))
  (:metaclass xhtml-meta))

(defclass elem-link (elem-global fragment)
  ((attr-target :initarg :target :accessor attr-target)
   (attr-urn :initarg :urn :accessor attr-urn)
   (attr-rev :initarg :rev :accessor attr-rev)
   (attr-methods :initarg :methods :accessor attr-methods)
   (attr-charset :initarg :charset :accessor attr-charset)
   (attr-fetchpriority :initarg :fetchpriority :accessor attr-fetchpriority)
   (attr-disabled :initarg :disabled :accessor attr-disabled)
   (attr-color :initarg :color :accessor attr-color)
   (attr-blocking :initarg :blocking :accessor attr-blocking)
   (attr-as :initarg :as :accessor attr-as)
   (attr-sizes :initarg :sizes :accessor attr-sizes)
   (attr-imagesizes :initarg :imagesizes :accessor attr-imagesizes)
   (attr-imagesrcset :initarg :imagesrcset :accessor attr-imagesrcset)
   (attr-title :initarg :title :accessor attr-title)
   (attr-referrerpolicy :initarg :referrerpolicy :accessor attr-referrerpolicy)
   (attr-type :initarg :type :accessor attr-type)
   (attr-hreflang :initarg :hreflang :accessor attr-hreflang)
   (attr-integrity :initarg :integrity :accessor attr-integrity)
   (attr-media :initarg :media :accessor attr-media)
   (attr-crossorigin :initarg :crossorigin :accessor attr-crossorigin)
   (attr-rel :initarg :rel :accessor attr-rel)
   (attr-href :initarg :href :accessor attr-href))
  (:metaclass xhtml-meta))

(defclass elem-base (elem-global fragment)
  ((attr-target :initarg :target :accessor attr-target)
   (attr-href :initarg :href :accessor attr-href))
  (:metaclass xhtml-meta))

(defclass elem-title (elem-global fragment) ()
  (:metaclass xhtml-meta))

(defclass elem-head (elem-global fragment)
  ((attr-profile :initarg :profile :accessor attr-profile))
  (:metaclass xhtml-meta))

(defclass elem-html (elem-global fragment)
  ((attr-version :initarg :version :accessor attr-version)
   (attr-manifest :initarg :manifest :accessor attr-manifest))
  (:metaclass xhtml-meta))

